// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWzVFtQWfe_4zdwBQMQdygi3t5hFxrUQ',
    appId: '1:1051380588030:web:3da41eff9eb015047ab4af',
    messagingSenderId: '1051380588030',
    projectId: 'flutter-10f3e',
    authDomain: 'flutter-10f3e.firebaseapp.com',
    storageBucket: 'flutter-10f3e.firebasestorage.app',
    measurementId: 'G-1WYZ525PW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2sdhXDyn8iwKyCiyUKzvpiLSiX3TmFA',
    appId: '1:1051380588030:android:9a5be6b92ada4dbe7ab4af',
    messagingSenderId: '1051380588030',
    projectId: 'flutter-10f3e',
    storageBucket: 'flutter-10f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXrIAd7Fs2o4sDRnoPd2Tac97Z68epxc',
    appId: '1:1051380588030:ios:6508c88ef1d045627ab4af',
    messagingSenderId: '1051380588030',
    projectId: 'flutter-10f3e',
    storageBucket: 'flutter-10f3e.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXrIAd7Fs2o4sDRnoPd2Tac97Z68epxc',
    appId: '1:1051380588030:ios:6508c88ef1d045627ab4af',
    messagingSenderId: '1051380588030',
    projectId: 'flutter-10f3e',
    storageBucket: 'flutter-10f3e.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGWzVFtQWfe_4zdwBQMQdygi3t5hFxrUQ',
    appId: '1:1051380588030:web:1b709a295e1028fd7ab4af',
    messagingSenderId: '1051380588030',
    projectId: 'flutter-10f3e',
    authDomain: 'flutter-10f3e.firebaseapp.com',
    storageBucket: 'flutter-10f3e.firebasestorage.app',
    measurementId: 'G-4GKYDNK47W',
  );
}
